apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap
  namespace: market-application
  labels:
    app: client-configmap-label
data:
  application.yaml: |+
    server:
      port: 8082

    spring:
      jpa:
        hibernate:
          ddl-auto: update

      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver

    kafka:
      server: http://host.minikube.internal:39092
      offset-reset: latest
      topics:
        marketplace:
          create: marketplace.create.topic
          update: marketplace.update.topic
      groupid:
        buyer_account: groupid.marketplace.buyer_account.topic
        seller_account: groupid.marketplace.seller_account.topic
        inventory: groupid.marketplace.inventory.topic
        inbox: groupid.marketplace.inbox.topic
