server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true


kafka:
  server: localhost:29092
  topics:
    marketplace:
      create: marketplace.create.topic
      update: marketplace.update.topic


