server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/store?createDatabaseIfNotExist=true


kafka:
  server: kafka:9092
  topics:
    marketplace:
      create: marketplace.create.topic
      update: marketplace.update.topic


